site_name: Seismological Data Analysis (SDA)
repo_url: https://github.com/FlavienMattern/sda.git

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

  ### Palette configuration
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Dark Mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Light Mode

  ### Font configuration
  font:
    text: Roboto
    code: Roboto Mono

  ### Features configuration
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_toc_entry: false
            docstring_style: google
            merge_init_into_class: true
            extra:
              show_signature: true
              show_docstring: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - styles/style.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials:
    - Getting started: tutorials/getting_started.md
    - Dataset formatting: tutorials/dataset_format.md
    - Computing PPSD: tutorials/ppsd.md
    - Ambient Noise Correlations: tutorials/xcorr_noise.md
    - Inverting dv/v: tutorials/invert_dvv.md
  - SDA API:
    - sda.core:
        - function1: core/function1.md
        - inversion: core/inversion.md
    - sda.process:
        - download_data: process/download_data.md
        - scan_data: process/scan_data.md
        - xcorr_noise: process/xcorr_noise.md
        - xcorr_noise_postprocessing: process/xcorr_noise_postprocessing.md
        - xcorr_noise_monitoring: process/xcorr_noise_monitoring.md
  - References: references.md